In [1]:
import numpy as np
import pandas as pd

X = pd.read_csv(r"C:\Users\dhanu\OneDrive\Desktop\data_science_project\3_Feature_Eng & Data_Prep\Input_Output_Saved\X_INPUT_DATA")
Y = pd.read_csv(r"C:\Users\dhanu\OneDrive\Desktop\data_science_project\3_Feature_Eng & Data_Prep\Input_Output_Saved\Y_OUTPUT_LABELS")

In [2]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,TotalServices,TechServices_Support,AvgMonthlyCharges,ChargeInflationRatio,CostperService,IsNewCust,IsLongTermCust,IsMonth_to_Month,RiskyCustomerProfile,HasFamily
0,0,0,1,0,1,0,0,0,1,0,...,1,1,29.850000,1.000000,29.850000,1,0,1,1,1
1,1,0,0,0,34,1,0,1,0,1,...,3,2,55.573529,1.024768,18.983333,0,0,0,0,0
2,1,0,0,0,2,1,0,1,1,0,...,3,2,54.075000,0.995839,17.950000,1,0,1,0,0
3,1,0,0,0,45,0,0,1,0,1,...,3,3,40.905556,1.034089,14.100000,0,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,1,0,75.825000,0.932410,70.700000,1,0,1,1,0

In [3]:
Y.head()

   Churn
0      0
1      0
2      1
3      0
4      1

In [5]:
# splitting into training and test datasets

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42, stratify = Y)

In [9]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'PaperlessBilling', 'MonthlyCharges', 'InternetService_Fiber optic',
       'InternetService_No', 'Contract_One year', 'Contract_Two year',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'TotalCharges_log', 'TotalServices', 'TechServices_Support',
       'AvgMonthlyCharges', 'ChargeInflationRatio', 'CostperService',
       'IsNewCust', 'IsLongTermCust', 'IsMonth_to_Month',
       'RiskyCustomerProfile', 'HasFamily'],
      dtype='str')

In [10]:
# We have some continuous columns, which we have to scale for the training input dataset

scaler = StandardScaler()
cols_to_scale = ['tenure', 'MonthlyCharges', 'TotalCharges_log', 'CostperService', 'AvgMonthlyCharges']

x_train[cols_to_scale] = scaler.fit_transform(x_train[cols_to_scale])
x_test[cols_to_scale] = scaler.transform(x_test[cols_to_scale])

print(f"x_train shape : {x_train.shape} || x_test shape : {x_test.shape}")

x_train shape : (5634, 33) || x_test shape : (1409, 33)

The dataset (training and test) are both prepared and properly scaled, and ready for model training.

In [11]:
x_train.to_csv(r"C:\Users\dhanu\OneDrive\Desktop\data_science_project\3_Feature_Eng & Data_Prep\Training_and_Test_datasets\x_train", index = False)
x_test.to_csv(r"C:\Users\dhanu\OneDrive\Desktop\data_science_project\3_Feature_Eng & Data_Prep\Training_and_Test_datasets\x_test", index = False)
y_train.to_csv(r"C:\Users\dhanu\OneDrive\Desktop\data_science_project\3_Feature_Eng & Data_Prep\Training_and_Test_datasets\y_train", index = False)
y_test.to_csv(r"C:\Users\dhanu\OneDrive\Desktop\data_science_project\3_Feature_Eng & Data_Prep\Training_and_Test_datasets\y_test", index = False)